<!-- Admin 资金入账流水主页面：只展示已提交结算资金事实和方向，不在前端重算净额、余额或汇率。 -->
<template>
    <div class="app-container settlement-list-page">
        <el-form v-show="showSearch" :model="query" inline size="small" class="search-form" label-width="92px">
            <el-form-item :label="t('transaction.settlement.ledgerNo')"><el-input v-model.trim="query.ledgerNo" clearable @keyup.enter="handleSearch" /></el-form-item>
            <el-form-item :label="t('transaction.settlement.batchNo')"><el-input v-model.trim="query.settlementBatchNo" clearable @keyup.enter="handleSearch" /></el-form-item>
            <el-form-item :label="t('transaction.fields.merchantId')"><MerchantRemoteSelect v-model="query.merchantId" @change="handleSearch" /></el-form-item>
            <el-form-item :label="t('transaction.clearing.direction')"><el-select v-model="query.direction" clearable :placeholder="t('common.pleaseSelect')"><el-option :label="enumText('directionValue','CREDIT')" value="CREDIT" /><el-option :label="enumText('directionValue','DEBIT')" value="DEBIT" /></el-select></el-form-item>
            <el-form-item :label="t('transaction.settlement.operationMode')"><el-select v-model="query.operationMode" clearable :placeholder="t('common.pleaseSelect')"><el-option :label="t('transaction.settlement.operationModeValue.AUTO')" value="AUTO" /><el-option :label="t('transaction.settlement.operationModeValue.MANUAL')" value="MANUAL" /></el-select></el-form-item>
            <el-form-item :label="t('transaction.settlement.currency')"><CurrencySelect v-model="query.currency" /></el-form-item>
            <el-form-item :label="t('transaction.settlement.postedTime')"><el-date-picker v-model="postedRange" type="datetimerange" value-format="YYYY-MM-DDTHH:mm:ss" format="YYYY-MM-DD HH:mm:ss" :clearable="false" :range-separator="t('common.to')" :start-placeholder="t('common.startTime')" :end-placeholder="t('common.endTime')" /></el-form-item>
            <el-form-item><el-button type="primary" :icon="Search" @click="handleSearch">{{t('common.search')}}</el-button><el-button :icon="RefreshLeft" @click="handleReset">{{t('common.reset')}}</el-button></el-form-item>
        </el-form>
        <el-row :gutter="10" class="mb8"><el-col :span="1.5"><el-button v-hasPermi="'settlement:posting:export'" type="warning" plain :icon="Download" :loading="exporting" @click="handleExport">{{t('common.export')}}</el-button></el-col><el-col class="right-toolbar"><RightToolbar @toggle-search="showSearch=!showSearch" @refresh="loadData" /></el-col></el-row>
        <StandardTable v-loading="loading" table-key="admin-settlement-postings" :data="rows" row-key="id" size="small">
            <el-table-column prop="ledgerNo" :label="t('transaction.settlement.ledgerNo')" min-width="220" fixed="left" align="center" show-overflow-tooltip />
            <el-table-column prop="settlementBatchNo" :label="t('transaction.settlement.batchNo')" min-width="205" align="center"><template #default="{row}"><el-button link type="primary" @click="openBatch(row.settlementBatchNo)">{{row.settlementBatchNo}}</el-button></template></el-table-column>
            <el-table-column prop="merchantId" :label="t('transaction.fields.merchantId')" min-width="140" align="center"><template #default="{row}"><el-button link type="primary" @click="openMerchant(row.merchantId)">{{row.merchantId}}</el-button></template></el-table-column>
            <el-table-column :label="t('transaction.settlement.businessType')" min-width="178" align="center"><template #default="{row}">{{enumText('businessTypeValue',row.businessType)}}</template></el-table-column>
            <el-table-column :label="t('transaction.clearing.direction')" width="96" align="center"><template #default="{row}"><DirectionTag :direction="row.direction" :label="enumText('directionValue',row.direction)" /></template></el-table-column>
            <el-table-column :label="t('transaction.settlement.postingAmount')" min-width="156" align="right"><template #default="{row}">{{moneyTextByExponent(row.amount,row.currency,row.currencyExponent)}}</template></el-table-column>
            <el-table-column :label="t('transaction.settlement.balanceBefore')" min-width="160" align="right"><template #default="{row}">{{moneyTextByExponent(row.balanceBefore,row.currency,row.currencyExponent)}}</template></el-table-column>
            <el-table-column :label="t('transaction.settlement.balanceAfter')" min-width="160" align="right"><template #default="{row}">{{moneyTextByExponent(row.balanceAfter,row.currency,row.currencyExponent)}}</template></el-table-column>
            <el-table-column :label="t('transaction.settlement.operationMode')" width="116" align="center"><template #default="{row}">{{enumText('operationModeValue',row.operationMode)}}</template></el-table-column>
            <el-table-column prop="operatorName" :label="t('transaction.settlement.submitter')" min-width="126" align="center" />
            <el-table-column prop="reviewerName" :label="t('transaction.settlement.reviewer')" min-width="126" align="center" />
            <el-table-column :label="t('transaction.settlement.postedTime')" min-width="174" align="center"><template #default="{row}"><BaseDateTime :value="row.postedTime" /></template></el-table-column>
            <el-table-column :label="t('common.operation')" width="92" fixed="right" align="center"><template #default="{row}"><el-button link type="primary" :icon="View" @click="openDetail(row)">{{t('common.detail')}}</el-button></template></el-table-column>
        </StandardTable>
        <div v-show="total>0" class="pagination-container"><el-pagination v-model:current-page="query.pageNo" v-model:page-size="query.pageSize" :total="total" :page-sizes="[10,20,50,100]" layout="total, sizes, prev, pager, next, jumper" background @current-change="loadData" @size-change="handleSearch" /></div>
        <el-drawer v-model="detailVisible" :title="t('transaction.settlement.postingDetail')" size="min(760px, 96vw)" destroy-on-close><el-descriptions v-if="detail" :column="2" border size="small">
            <el-descriptions-item :label="t('transaction.settlement.ledgerNo')" :span="2">{{detail.ledgerNo}}</el-descriptions-item><el-descriptions-item :label="t('transaction.settlement.batchNo')"><el-button link type="primary" @click="openBatch(detail.settlementBatchNo)">{{detail.settlementBatchNo}}</el-button></el-descriptions-item><el-descriptions-item :label="t('transaction.fields.merchantId')"><el-button link type="primary" @click="openMerchant(detail.merchantId)">{{detail.merchantId}}</el-button></el-descriptions-item>
            <el-descriptions-item :label="t('transaction.settlement.accountId')"><el-button link type="primary" @click="openAccount(detail)">{{detail.accountId}}</el-button></el-descriptions-item><el-descriptions-item :label="t('transaction.settlement.accountSequence')">{{detail.accountSequence}}</el-descriptions-item>
            <el-descriptions-item :label="t('transaction.settlement.businessType')">{{enumText('businessTypeValue',detail.businessType)}}</el-descriptions-item><el-descriptions-item :label="t('transaction.settlement.operationMode')">{{enumText('operationModeValue',detail.operationMode)}}</el-descriptions-item>
            <el-descriptions-item :label="t('transaction.settlement.postingAmount')">{{moneyTextByExponent(detail.amount,detail.currency,detail.currencyExponent)}}</el-descriptions-item><el-descriptions-item :label="t('transaction.clearing.direction')"><DirectionTag :direction="detail.direction" :label="enumText('directionValue',detail.direction)" /></el-descriptions-item>
            <el-descriptions-item :label="t('transaction.settlement.balanceBefore')">{{moneyTextByExponent(detail.balanceBefore,detail.currency,detail.currencyExponent)}}</el-descriptions-item><el-descriptions-item :label="t('transaction.settlement.balanceAfter')">{{moneyTextByExponent(detail.balanceAfter,detail.currency,detail.currencyExponent)}}</el-descriptions-item>
            <el-descriptions-item :label="t('transaction.settlement.submitter')">{{detail.operatorName||'-'}}</el-descriptions-item><el-descriptions-item :label="t('transaction.settlement.reviewer')">{{detail.reviewerName||'-'}}</el-descriptions-item>
            <el-descriptions-item :label="t('transaction.clearing.reason')" :span="2">{{detail.operationReason||'-'}}</el-descriptions-item><el-descriptions-item :label="t('transaction.settlement.reviewComment')" :span="2">{{detail.reviewComment||'-'}}</el-descriptions-item>
            <el-descriptions-item :label="t('transaction.settlement.ledgerIdempotencyKey')" :span="2">{{detail.idempotencyKey}}</el-descriptions-item><el-descriptions-item :label="t('transaction.settlement.reversalOfLedgerId')">{{detail.reversalOfLedgerId||'-'}}</el-descriptions-item><el-descriptions-item :label="t('transaction.settlement.postedTime')"><BaseDateTime :value="detail.postedTime" /></el-descriptions-item>
        </el-descriptions></el-drawer>
    </div>
</template>
<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue';import { Download,RefreshLeft,Search,View } from '@element-plus/icons-vue';import { ElMessage } from 'element-plus';import { DirectionTag } from '@acquiring/shared';import { useI18n } from 'vue-i18n';import { useRoute,useRouter } from 'vue-router';import { exportSettlementPostings,searchSettlementPostings,type SettlementPosting,type SettlementPostingQuery } from '@/api/settlement';import BaseDateTime from '@/components/BaseDateTime/index.vue';import RightToolbar from '@/components/RightToolbar/index.vue';import StandardTable from '@/components/StandardTable/StandardTable.vue';import CurrencySelect from '@/views/exchange/CurrencySelect.vue';import MerchantRemoteSelect from '@/views/transaction/components/MerchantRemoteSelect.vue';import { defaultDateTimeRange,moneyTextByExponent } from '@/views/settlement/shared';
const {t,te}=useI18n();const route=useRoute(),router=useRouter();const showSearch=ref(true),loading=ref(false),exporting=ref(false),detailVisible=ref(false);const rows=ref<SettlementPosting[]>([]),total=ref(0),detail=ref<SettlementPosting|null>(null),postedRange=ref<[string,string]>(defaultDateTimeRange());const query=reactive<SettlementPostingQuery>({beginPostedTime:'',endPostedTime:'',pageNo:1,pageSize:10});onMounted(()=>{const linked=typeof route.query.settlementBatchNo==='string'?route.query.settlementBatchNo.trim():'';const postedDate=typeof route.query.postedDate==='string'?route.query.postedDate.trim():'';if(linked)query.settlementBatchNo=linked;if(/^\d{4}-\d{2}-\d{2}$/.test(postedDate))postedRange.value=[`${postedDate}T00:00:00`,`${postedDate}T23:59:59`];loadData()});function enumText(group:string,value?:string){if(!value)return'-';const key=`transaction.settlement.${group}.${value}`;return te(key)?t(key):value}
function requestQuery():SettlementPostingQuery{return{...query,settlementBatchNo:query.settlementBatchNo||undefined,merchantId:query.merchantId||undefined,ledgerNo:query.ledgerNo||undefined,direction:query.direction||undefined,operationMode:query.operationMode||undefined,currency:query.currency||undefined,beginPostedTime:postedRange.value[0],endPostedTime:postedRange.value[1]}}
async function loadData(){loading.value=true;try{const result=await searchSettlementPostings(requestQuery());rows.value=result.records||[];total.value=result.total||0}catch(error){ElMessage.error(error instanceof Error?error.message:t('common.loadFailed'))}finally{loading.value=false}}function handleSearch(){query.pageNo=1;loadData()}function handleReset(){Object.assign(query,{settlementBatchNo:undefined,merchantId:undefined,ledgerNo:undefined,direction:undefined,operationMode:undefined,currency:undefined,pageNo:1});postedRange.value=defaultDateTimeRange();loadData()}async function handleExport(){exporting.value=true;try{await exportSettlementPostings(requestQuery())}catch(error){ElMessage.error(error instanceof Error?error.message:t('common.exportFailed'))}finally{exporting.value=false}}function openDetail(row:SettlementPosting){detail.value=row;detailVisible.value=true}
function openBatch(settlementBatchNo:string){router.push({path:'/settlement/batches',query:{settlementBatchNo}})}function openMerchant(merchantId:string){router.push({path:'/merchant/info',query:{merchantId}})}
function openAccount(row:SettlementPosting){router.push({path:'/fund/account',query:{merchantId:row.merchantId,settlementCurrency:row.currency}})}
</script>
<style scoped>.search-form :deep(.el-input),.search-form :deep(.el-select){width:220px}.search-form :deep(.el-date-editor){width:372px}</style>
